Urban Data Science & Smart Cities <br>
URSP688Y Spring 2025<br>
Instructor: Chester Harvey <br>
Urban Studies & Planning <br>
National Center for Smart Growth <br>
University of Maryland

# Demo 4 - Loading and Joining Data From Files

- Table gymnastics (a.k.a., data wrangling)
    - Load data from a CSV
    - Practice exploring the data
    - Convert dates stored as strings to `datetime` data types
    - Drop duplicate rows
    - Count rows withing groups
    - Concatenate tables
    - Join columns from another table
- Debugging

In [2]:
# Import packages
import pandas as pd

## Loading Data from a File

Let's get our hands on some real-world data by loading a table from a file.

Let's load data from the [Maryland Eviction Case Database](https://opendata.maryland.gov/Housing/District-Court-of-Maryland-Eviction-Case-Data/mvqb-b4hf/data).

A CSV file that is stored in the same directory as our notebook can be opened by entering just the file name as an argument to `pd.read_csv`.

In [3]:
# ! Load the eviction cases CSV

df = pd.read_csv('District_Court_of_Maryland_Eviction_Case_Data_MG_PG.csv')
df['Event Date'] = pd.to_datetime(df['Event Date'])
df['Tenant ZIP Code'] = df['Tenant ZIP Code'].astype('Int64')

Let's practice navigating and doing some analysis with our DataFrame.

Preview the dataframe

In [4]:
# ! Show the df head

In [5]:
df.head

<bound method NDFrame.head of        Unnamed: 0 Event Date  \
0               0 2023-01-03
1               1 2023-01-03
2               2 2023-01-03
3               3 2023-01-03
4               4 2023-01-03
...           ...        ...
96072       96072 2024-12-27
96073       96073 2024-12-31
96074       96074 2024-12-20
96075       96075 2024-12-26
96076       96076 2024-12-31

                                              Event Type  \
0      Warrant of Restitution - Return of Service - E...
1      Warrant of Restitution - Return of Service - E...
2      Warrant of Restitution - Return of Service - E...
3      Warrant of Restitution - Return of Service - E...
4      Warrant of Restitution - Return of Service - E...
...                                                  ...
96072        Petition - For Warrant of Restitution Filed
96073        Petition - For Warrant of Restitution Filed
96074        Petition - For Warrant of Restitution Filed
96075        Petition - For Warrant of Restitution Filed
96076        Petition - For Warrant of Restitution Filed

                                 Event Comment           County     Location  \
0                                          NaN       Montgomery    Rockville
1                                          NaN       Montgomery    Rockville
2                                          NaN       Montgomery    Rockville
3                                          NaN       Montgomery    Rockville
4                                          NaN       Montgomery    Rockville
...                                        ...              ...          ...
96072  LIVE MO RECEIVED FOR $40 - #29583229140  Prince George's  Hyattsville
96073                                      NaN  Prince George's  Hyattsville
96074      Petition for Warrant of Restitution  Prince George's  Hyattsville
96075       LIVE CHECK RECEIVED FOR $40 - $485  Prince George's  Hyattsville
96076      LIVE CHECK RECEIVED FOR $40 - #2237  Prince George's  Hyattsville

          Tenant City Tenant State  Tenant ZIP Code            Case Type  \
0       Silver Spring           MD            20910  Failure to Pay Rent
1       Silver Spring           MD            20910  Failure to Pay Rent
2            Bethesda           MD            20814  Failure to Pay Rent
3       Silver Spring           MD            20902  Failure to Pay Rent
4           Rockville           MD            20850  Failure to Pay Rent
...               ...          ...              ...                  ...
96072       RIVERDALE           MD            20737  Failure to Pay Rent
96073       GREENBELT           MD            20770    Wrongful Detainer
96074  Ft. Washington           MD            20744    Wrongful Detainer
96075          LANHAM           MD            20706  Failure to Pay Rent
96076  UPPER MARLBORO           MD            20774  Failure to Pay Rent

              Case Number Evicted Date  Event Year  Eviction Year
0      D-061-LT-22-004107   12/08/2022      2023.0         2022.0
1      D-061-LT-22-000755   12/08/2022      2023.0         2022.0
2      D-061-LT-22-000816   12/07/2022      2023.0         2022.0
3      D-061-LT-22-006362   12/08/2022      2023.0         2022.0
4      D-061-LT-22-004268   12/07/2022      2023.0         2022.0
...                   ...          ...         ...            ...
96072  D-051-LT-24-001507          NaN      2024.0            NaN
96073   D-05-CV-24-049442          NaN      2024.0            NaN
96074   D-05-CV-24-049487          NaN      2024.0            NaN
96075  D-051-LT-24-001516          NaN      2024.0            NaN
96076  D-051-LT-24-001524          NaN      2024.0            NaN

[96077 rows x 14 columns]>

How many rows does it have?

In [6]:
# ! Show df length

len(df) #helpful way to see how much data

96077

What columns does it have?

In [7]:
# ! Show df columns

df.columns.tolist()

['Unnamed: 0',
 'Event Date',
 'Event Type',
 'Event Comment',
 'County',
 'Location',
 'Tenant City',
 'Tenant State',
 'Tenant ZIP Code',
 'Case Type',
 'Case Number',
 'Evicted Date',
 'Event Year',
 'Eviction Year']

Which counties are represented?

In [8]:
# ! Show value counts for county column

df['County'].value_counts()

County
Prince George's    67003
Montgomery         29074
Name: count, dtype: int64

What is the earlist date?

Is this true?

In [20]:
# ! Sort by date

df.sort_values('Event Date')
#This sorts by numerical value, not by date value. Helpful to find data type

,Unnamed: 0,Event Date,Event Type,Event Comment,County,Location,Tenant City,Tenant State,Tenant ZIP Code,Case Type,Case Number,Evicted Date,Event Year,Eviction Year
0,0,2023-01-03,Warrant of Restitution - Return of Service - E...,NaN,Montgomery,Rockville,Silver Spring,MD,20910,Failure to Pay Rent,D-061-LT-22-004107,12/08/2022,2023.0,2022.0
5,5,2023-01-03,Warrant of Restitution - Return of Service - E...,NaN,Montgomery,Rockville,Rockville,MD,20850,Failure to Pay Rent,D-061-LT-22-004289,12/07/2022,2023.0,2022.0
8,8,2023-01-03,Warrant of Restitution - Return of Service - E...,NaN,Montgomery,Rockville,Silver Spring,MD,20906,Failure to Pay Rent,D-061-LT-22-015132,01/03/2023,2023.0,2023.0
7,7,2023-01-03,Warrant of Restitution - Return of Service - E...,NaN,Montgomery,Rockville,Silver Spring,MD,20906,Failure to Pay Rent,D-061-LT-22-015154,01/03/2023,2023.0,2023.0
6,6,2023-01-03,Warrant of Restitution - Return of Service - E...,NaN,Montgomery,Rockville,Silver Spring,MD,20902,Failure to Pay Rent,D-061-LT-22-006357,12/08/2022,2023.0,2022.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96057,96057,2024-12-31,Petition - For Warrant of Restitution Filed,OFFIT::Warrant of Restitution,Prince George's,Hyattsville,Forestville,MD,20747,Failure to Pay Rent,D-05-LT-24-40005-009,NaN,2024.0,NaN
96058,96058,2024-12-31,Petition - For Warrant of Restitution Filed,OFFIT::Warrant of Restitution,Prince George's,Hyattsville,Forestville,MD,20747,Failure to Pay Rent,D-05-LT-24-40005-011,NaN,2024.0,NaN
93918,93918,2024-12-31,Petition - For Warrant of Restitution Filed,EWRIT::Warrant of Restitution,Montgomery,Rockville,Silver Spring,MD,20901,Failure to Pay Rent,D-06-LT-24-39056-016,NaN,2024.0,NaN
96073,96073,2024-12-31,Petition - For Warrant of Restitution Filed,NaN,Prince George's,Hyattsville,GREENBELT,MD,20770,Wrongful Detainer,D-05-CV-24-049442,NaN,2024.0,NaN
96076,96076,2024-12-31,Petition - For Warrant of Restitution Filed,LIVE CHECK RECEIVED FOR $40 - #2237,Prince George's,Hyattsville,UPPER MARLBORO,MD,20774,Failure to Pay Rent,D-051-LT-24-001524,NaN,2024.0,NaN

In [21]:
df['Event Date'] = pd.to_datetime(df['Event Date'])

In [22]:
df.sort_values('Event Date', ascending=True).head(2)

,Unnamed: 0,Event Date,Event Type,Event Comment,County,Location,Tenant City,Tenant State,Tenant ZIP Code,Case Type,Case Number,Evicted Date,Event Year,Eviction Year
0,0,2023-01-03,Warrant of Restitution - Return of Service - E...,NaN,Montgomery,Rockville,Silver Spring,MD,20910,Failure to Pay Rent,D-061-LT-22-004107,12/08/2022,2023.0,2022.0
5,5,2023-01-03,Warrant of Restitution - Return of Service - E...,NaN,Montgomery,Rockville,Rockville,MD,20850,Failure to Pay Rent,D-061-LT-22-004289,12/07/2022,2023.0,2022.0

Convert the event date column to a `datetime` data type

In [19]:
# ! Convert date column to datetime type #to avoid doing it as a string


#pandas convert to datetime


pd.to_datetime(df['Event Date'])#converts from string to integer

0       2023-01-03
1       2023-01-03
2       2023-01-03
3       2023-01-03
4       2023-01-03
           ...
96072   2024-12-27
96073   2024-12-31
96074   2024-12-20
96075   2024-12-26
96076   2024-12-31
Name: Event Date, Length: 96077, dtype: datetime64[ns]

How many unique cases are there?

In [13]:
df = df.sort_values('Event Date', ascending=True)

#Ascending, true, smallest to largest

In [16]:
# ! Drop duplicate case numbers after sorting so first event is maintained

#df = df.drop_duplicates(subset='Case Number', keep='first') 

df_dedup = df.sort_values('Event Date', ascending=True).drop_duplicates(subset='Case Number', keep='first')
#Options: subset, keep

#Look into how many unique cases there are in case

How many unique cases per zip code?

In [17]:
cases_per_zip = df_dedup.groupby('Tenant ZIP Code')['Case Number'].count().sort_values(ascending=False)

cases_per_zip

Tenant ZIP Code
20746    5490
20770    5013
20747    4495
20748    4001
20708    3710
         ...
21746       1
21771       1
22769       1
27048       1
55403       1
Name: Case Number, Length: 128, dtype: int64

In [18]:
# Count cases within each zip code
#df.groupby('Tenant ZIP Code')['Case Number'].count()sort_values()

cases_per_zip = df_dedup.groupby('Tenant ZIP Code')['Case Number'].count().sort_values(ascending=False)
cases_per_zip

# ! Group by zip code and count unique cases

Tenant ZIP Code
20746    5490
20770    5013
20747    4495
20748    4001
20708    3710
         ...
21746       1
21771       1
22769       1
27048       1
55403       1
Name: Case Number, Length: 128, dtype: int64

In [19]:
# Convert results to a dataframe with a column for zip and a column for cases

# ! Convert to dataframe and clean up columns


cases_per_zip = pd.DataFrame(cases_per_zip).reset_index()
cases_per_zip = cases_per_zip.rename(columns={'Tenant ZIP Code':'case_zip','Case Number':'case_count'})

cases_per_zip.head()

   case_zip  case_count
0     20746        5490
1     20770        5013
2     20747        4495
3     20748        4001
4     20708        3710

Which zip codes have the most unique cases per person?

Let's join data from [CensusReporter](https://censusreporter.org/).

### Combining/Merging/Joining Tables

Combining information from multiple tables into a single table is one of the most useful data wrangling operations.

There are lots of different ways to join tables, but two basic types are:

1. Joining column with a shared key, which outputs a table that is wider than either input.
2. Concatenating rows with shared column names, which outputs a table that is longer than either input.

#### Joining columns based on a key

![joining columns with a shared key](https://rforhr.com/horizontal_join.png)


#### Concatenating rows with the same column names
![joining rows with shared column names](https://rforhr.com/vertical_join.png)

First, let's concatenate census tables for Montgomery and Prince George's county to make a single table with populations for each zip code.

Then, we'll merge counts of eviction cases onto each zip code.

Finally, we'll calcuate the number of eviction cases per capita.

In [23]:
# Load census reporter data, ignoring the row with data for the whole county (first row under the header)

#def load_census_reporter_csv(path): #function to read CSV
#df_census_mg = pd.read_csv('acs2023_5yr_B01003_mg.csv', skiprows=[1])
#df_census_pg = load_census_reporter_csv('acs2023_5yr_B01003_pg.csv') 


def load_census_reporter_csv(path, skiprows=[1]):
    return pd.read_csv(path, skiprows=skiprows)

df_pop_mg = load_census_reporter_csv('acs2023_5yr_B01003_mg.csv')
df_pop_pg = load_census_reporter_csv('acs2023_5yr_B01003_pg.csv') 


# ! Write a function to load census reporter data

In [24]:
# Combine into a single dataframe
# ! Concatenate dataframes

df_pop = pd.concat([df_pop_mg, df_pop_pg], axis=0)

In [25]:
# Rename columns with readable names
df_pop = df_pop.rename(columns={'name':'census_zip', 'B01003001':'population', 'B01003001, Error':'population_error'})


#df_census.rename(columns={'name': 'census_zip',})
#df_census = df_census.drop(column=[])
# ! Clean up column names

In [26]:
# Merge the case counts onto the zip codes

df_pop.head()
df_pop.census_zip.dtype



# ! Ensure that zipcode columns in both dataframes are the same data type

dtype('int64')

In [27]:
#event_counts.head()
cases_per_zip.head()

   case_zip  case_count
0     20746        5490
1     20770        5013
2     20747        4495
3     20748        4001
4     20708        3710

In [ ]:
event_zip.head()

In [28]:
cases_per_zip['case_zip'] = cases_per_zip['case_zip'].astype('int64').astype('string')
df_pop['census_zip'] = df_pop['census_zip'].astype('string')

In [29]:
df_pop = df_pop.merge(cases_per_zip, left_on='census_zip', right_on='case_zip', how='left')

In [30]:
df_pop.head()

          geoid census_zip  population  population_error case_zip  case_count
0  86000US20705      20705       28119              1864    20705      1002.0
1  86000US20707      20707       36549              1231    20707      1101.0
2  86000US20777      20777        3046               543     <NA>         NaN
3  86000US20812      20812         314               117     <NA>         NaN
4  86000US20814      20814       30822              1739    20814       185.0

In [31]:
# ! Merge on zipcode

# Cleanup

df_pop['case_count'] = df_pop['case_count'].fillna(0)
df_pop = df_pop.drop(columns=['population_error','case_zip'])

# ! Clean up column names

In [ ]:
# Calculate cases per capita

event_counts['event_count'] / event_counts['population']
# ! Calc new column and sort descending

In [ ]:
event_counts/sort_values('events_per_pop')

## Errors and debugging

Errors are frustrating and inevitable. Even professional programmers probably spend most of their time debugging.

Luckily, there are good tools and techniques for making debugging a little easier.

Despite these, you will probably nearly tear your hair out with some frequency, especially as a beginner. It will get better with time.

There are two types of errors in programming: logic and syntax. They both result in your program not achieving its goal, but the first may not be as easily detectable because the code may still run.

### Logic errors
These are issues with how you have approached or executed your problem. If your code runs but produces nonsensical results, there is probably a logic error. However, your erroneous code might also produce logical but *wrong* results; you might never notice until the problem has rippled downstream. It's best to address this proactively by planning your code well so it's less likely to be illogical, and writing readable code that can be easily reviewed.

Here's a logic error. Can you find it? (Hint: the issue is syntactical, but it's still a logic error because the code works without throwing an error.)

In [ ]:
def check_adult(age, cutoff=18):
    if age > cutoff:
        adult = False
    else:
        adult = True
    return adult

check_adult(20)

### Syntax errors
These are more obvious because your code will simply fail. There are lots of tools for figuring out where and why.

Error messages are usually the starting place for debugging a syntax error.

In [ ]:
def check_adult(age, cutoff=18):
    if age < cutoff:
        adult = False
    else:
        adult = True
    return adult

check_adult('20')

The error message tells us where the problem is located.

Sometimes, it can be helpful to turn on line numbers.
- In Colab: `Tools -> Settings -> Editor -> Show line numbers`
- In JupyterLab: `View -> Show Line Numbers`

The `ValueError` tells us that the issue is related to the value of a variable on this line, but it's still pretty vague.

Time to start [Googling](https://www.google.com/).

### Debugging
We can also use an "interactive debugger" to help diagnose our problem by stepping through the code one line at a time.

The debugger provides tools for setting "breakpoints" where the code will stop running temporarily, a table that shows the values of variables at that time, and buttons to start, stop, and step through the code.

https://jupyterlab.readthedocs.io/en/stable/user/debugger.html

In [ ]:
def check_adult(age, cutoff=18):
    if age < cutoff:
        adult = False
    else:
        adult = True
    return adult

check_adult(20)

## Style guidelines for Python
- At the very least, do things consistently
- One statement per line
- Try to limit line length to 72 characters
- Use four spaces to indent
- Put spaces around operators (e.g., `1 + 1` or `day = 'Monday'`) (except in keyword function arguments)
- Use blank lines intentionally and consistently
- Use meaningful names
- Name variables and functions with `lowercase_underscores`
- Constants are often named in `ALL_CAPS_WITH_UNDERSCORES` (e.g., `C = 2.99792458e+8`)
- Name custom classes with `CapWords`
- In general, avoid spaces in folder and filenames used for programming

See [Code Readability](https://github.com/ncsg/ursp688y_sp2024/blob/main/README.md#code-readability) on the syllabus. [CS61A](https://cs61a.org/articles/composition/) has an excellent composition guide. [PEP 8](https://peps.python.org/pep-0008/) is a standard Python style guide. [Google](https://google.github.io/styleguide/pyguide.html) publishes their internal Python style guide.